tools:
  exceptions: https://analytics.google.com/analytics/web/#/p222957178
  logging: ""
  ci: https://github.com/dcsil/try-studio/actions

services:
  production: https://dcsil.github.io/try-studio

docs:
  getting_started: https://github.com/dcsil/try-studio
      
commands:
  bootstrap: scripts/bootstrap.sh
  database: https://console.firebase.google.com/project/try-studio
  server: https://try-studio.herokuapp.com
  test:
    - cd client && yarn test
    - cd server && yarn test
