tools:
  exceptions:
    - https://analytics.google.com/analytics/web/#/p222957178
    - https://console.firebase.google.com/project/try-studio
  logging: null
  ci: https://github.com/dcsil/try-studio/actions

services:
  client: https://dcsil.github.io/try-studio
  server: https://try-studio.herokuapp.com

docs:
  getting_started: https://github.com/dcsil/try-studio
      
commands:
  bootstrap: scripts/bootstrap
